export interface Match {
  id: string;
  job_id: string;
  job_title: string;
  service_line: string;
  department: string;
  location: string;
  posted_date: string;
  experience_required: string;
  overall_score: number;
  skill_match_score: number;
  experience_score: number;
  growth_potential_score: number;
  matched_skills: string[];
  skill_gaps: string[];
  explanation: string;
  salary_range?: string;
  job_posting_url?: string;
}

export const MOCK_MATCHES_BEST_FIT: Match[] = [
  {
    id: "match-bf-001",
    job_id: "job-001",
    job_title: "Data Engineer",
    service_line: "Advisory",
    department: "Technology Consulting",
    location: "New York, NY",
    posted_date: "2026-01-03",
    experience_required: "3-7 years",
    overall_score: 0.92,
    skill_match_score: 0.95,
    experience_score: 0.90,
    growth_potential_score: 0.30,
    matched_skills: ["Python", "AWS", "Data Analysis"],
    skill_gaps: ["SQL", "ETL"],
    explanation: "This role is an excellent fit for your Python and AWS expertise. Your data analysis background provides a strong foundation. You'll need to develop SQL and ETL skills, which are highly learnable.",
    salary_range: "$100k - $130k",
    job_posting_url: "https://careers.ey.com/jobs/data-engineer-001"
  },
  {
    id: "match-bf-002",
    job_id: "job-002",
    job_title: "Cloud Solutions Architect",
    service_line: "Consulting",
    department: "Infrastructure Advisory",
    location: "Remote",
    posted_date: "2026-01-05",
    experience_required: "5-10 years",
    overall_score: 0.90,
    skill_match_score: 0.93,
    experience_score: 0.88,
    growth_potential_score: 0.25,
    matched_skills: ["AWS", "Cloud Architecture", "Client Management"],
    skill_gaps: ["Azure", "GCP"],
    explanation: "Your AWS expertise and client management skills make you an ideal candidate. This role offers the chance to expand into multi-cloud environments with Azure and GCP.",
    salary_range: "$120k - $150k"
  },
  {
    id: "match-bf-003",
    job_id: "job-003",
    job_title: "Senior Data Analyst",
    service_line: "Advisory",
    department: "Analytics",
    location: "Chicago, IL",
    posted_date: "2026-01-04",
    experience_required: "3-5 years",
    overall_score: 0.94,
    skill_match_score: 0.96,
    experience_score: 0.92,
    growth_potential_score: 0.20,
    matched_skills: ["Python", "Data Analysis", "Client Management"],
    skill_gaps: ["Tableau", "Power BI"],
    explanation: "Perfect alignment with your core skills. This role leverages your Python and data analysis expertise while introducing you to visualization tools that are easy to learn.",
    salary_range: "$95k - $115k"
  },
  {
    id: "match-bf-004",
    job_id: "job-004",
    job_title: "AWS Cloud Consultant",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "Boston, MA",
    posted_date: "2026-01-06",
    experience_required: "4-8 years",
    overall_score: 0.91,
    skill_match_score: 0.94,
    experience_score: 0.89,
    growth_potential_score: 0.28,
    matched_skills: ["AWS", "Python", "Client Management"],
    skill_gaps: ["Terraform", "Kubernetes"],
    explanation: "Strong match for your AWS and Python skills. The infrastructure-as-code gap is easily bridgeable with your technical background.",
    salary_range: "$110k - $140k"
  },
  {
    id: "match-bf-005",
    job_id: "job-005",
    job_title: "Data Strategy Consultant",
    service_line: "Advisory",
    department: "Analytics",
    location: "New York, NY",
    posted_date: "2026-01-02",
    experience_required: "5-7 years",
    overall_score: 0.93,
    skill_match_score: 0.92,
    experience_score: 0.95,
    growth_potential_score: 0.22,
    matched_skills: ["Data Analysis", "Client Management", "Python"],
    skill_gaps: ["Data Governance", "Strategy Frameworks"],
    explanation: "Excellent fit combining your technical data skills with client-facing experience. Strategy frameworks are learnable through on-the-job training.",
    salary_range: "$115k - $145k"
  },
  {
    id: "match-bf-006",
    job_id: "job-006",
    job_title: "Python Developer - Data Platform",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "Remote",
    posted_date: "2026-01-07",
    experience_required: "3-6 years",
    overall_score: 0.95,
    skill_match_score: 0.97,
    experience_score: 0.93,
    growth_potential_score: 0.18,
    matched_skills: ["Python", "AWS", "Data Analysis"],
    skill_gaps: ["Docker", "CI/CD"],
    explanation: "Nearly perfect match for your Python expertise. DevOps skills are standard in modern development and easily acquired.",
    salary_range: "$100k - $125k"
  },
  {
    id: "match-bf-007",
    job_id: "job-007",
    job_title: "Client-Facing Data Consultant",
    service_line: "Advisory",
    department: "Analytics",
    location: "San Francisco, CA",
    posted_date: "2026-01-01",
    experience_required: "4-7 years",
    overall_score: 0.92,
    skill_match_score: 0.91,
    experience_score: 0.94,
    growth_potential_score: 0.24,
    matched_skills: ["Client Management", "Data Analysis", "Python"],
    skill_gaps: ["Salesforce", "CRM Tools"],
    explanation: "Ideal role combining your technical and client management strengths. CRM tools are straightforward to learn.",
    salary_range: "$110k - $135k"
  },
  {
    id: "match-bf-008",
    job_id: "job-008",
    job_title: "Cloud Data Engineer",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "New York, NY",
    posted_date: "2026-01-08",
    experience_required: "3-5 years",
    overall_score: 0.94,
    skill_match_score: 0.95,
    experience_score: 0.92,
    growth_potential_score: 0.26,
    matched_skills: ["AWS", "Python", "Data Analysis"],
    skill_gaps: ["Spark", "Data Lakes"],
    explanation: "Strong technical match. Big data technologies like Spark are learnable with your Python foundation.",
    salary_range: "$105k - $130k"
  },
  {
    id: "match-bf-009",
    job_id: "job-009",
    job_title: "Analytics Consultant",
    service_line: "Advisory",
    department: "Analytics",
    location: "Chicago, IL",
    posted_date: "2026-01-05",
    experience_required: "4-6 years",
    overall_score: 0.91,
    skill_match_score: 0.93,
    experience_score: 0.90,
    growth_potential_score: 0.21,
    matched_skills: ["Data Analysis", "Python", "Client Management"],
    skill_gaps: ["Statistical Modeling", "R"],
    explanation: "Great fit for your analytical skills. Statistical modeling builds naturally on your data analysis background.",
    salary_range: "$100k - $125k"
  },
  {
    id: "match-bf-010",
    job_id: "job-010",
    job_title: "AWS Solutions Specialist",
    service_line: "Consulting",
    department: "Infrastructure Advisory",
    location: "Remote",
    posted_date: "2026-01-04",
    experience_required: "3-7 years",
    overall_score: 0.93,
    skill_match_score: 0.96,
    experience_score: 0.91,
    growth_potential_score: 0.23,
    matched_skills: ["AWS", "Python", "Client Management"],
    skill_gaps: ["CloudFormation", "Lambda"],
    explanation: "Excellent AWS match. Advanced AWS services are learnable through certification and hands-on practice.",
    salary_range: "$105k - $135k"
  },
  {
    id: "match-bf-011",
    job_id: "job-011",
    job_title: "Data Platform Engineer",
    service_line: "Advisory",
    department: "Technology Consulting",
    location: "Boston, MA",
    posted_date: "2026-01-06",
    experience_required: "5-8 years",
    overall_score: 0.90,
    skill_match_score: 0.92,
    experience_score: 0.89,
    growth_potential_score: 0.27,
    matched_skills: ["Python", "AWS", "Data Analysis"],
    skill_gaps: ["Airflow", "Data Pipelines"],
    explanation: "Strong technical foundation. Workflow orchestration tools are standard in data engineering and easily learned.",
    salary_range: "$115k - $145k"
  },
  {
    id: "match-bf-012",
    job_id: "job-012",
    job_title: "Cloud Analytics Consultant",
    service_line: "Consulting",
    department: "Analytics",
    location: "New York, NY",
    posted_date: "2026-01-03",
    experience_required: "4-6 years",
    overall_score: 0.92,
    skill_match_score: 0.94,
    experience_score: 0.91,
    growth_potential_score: 0.25,
    matched_skills: ["AWS", "Data Analysis", "Client Management"],
    skill_gaps: ["Redshift", "Athena"],
    explanation: "Perfect blend of your cloud and analytics skills. AWS analytics services are intuitive with your existing AWS knowledge.",
    salary_range: "$110k - $140k"
  }
];

export const MOCK_MATCHES_STRETCH: Match[] = [
  {
    id: "match-st-001",
    job_id: "job-101",
    job_title: "Senior Data Scientist",
    service_line: "Consulting",
    department: "Analytics",
    location: "New York, NY",
    posted_date: "2026-01-02",
    experience_required: "5-10 years",
    overall_score: 0.78,
    skill_match_score: 0.75,
    experience_score: 0.72,
    growth_potential_score: 0.65,
    matched_skills: ["Python", "Data Analysis"],
    skill_gaps: ["Machine Learning", "Statistics", "R"],
    explanation: "This is a stretch role that leverages your Python and data analysis skills while offering significant learning opportunities in ML and statistics. Perfect for career growth.",
    salary_range: "$130k - $160k"
  },
  {
    id: "match-st-002",
    job_id: "job-102",
    job_title: "DevOps Engineer",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "Remote",
    posted_date: "2026-01-04",
    experience_required: "4-8 years",
    overall_score: 0.75,
    skill_match_score: 0.70,
    experience_score: 0.80,
    growth_potential_score: 0.70,
    matched_skills: ["AWS", "Python"],
    skill_gaps: ["Kubernetes", "Docker", "CI/CD", "Terraform"],
    explanation: "Your AWS and Python skills provide a solid foundation. DevOps practices are learnable and this role offers excellent growth potential.",
    salary_range: "$115k - $145k"
  },
  {
    id: "match-st-003",
    job_id: "job-103",
    job_title: "Machine Learning Engineer",
    service_line: "Advisory",
    department: "Analytics",
    location: "San Francisco, CA",
    posted_date: "2026-01-01",
    experience_required: "3-7 years",
    overall_score: 0.72,
    skill_match_score: 0.68,
    experience_score: 0.76,
    growth_potential_score: 0.75,
    matched_skills: ["Python", "Data Analysis"],
    skill_gaps: ["TensorFlow", "PyTorch", "MLOps", "Deep Learning"],
    explanation: "Strong Python foundation positions you well. ML frameworks are learnable and this role offers cutting-edge experience.",
    salary_range: "$120k - $150k"
  },
  {
    id: "match-st-004",
    job_id: "job-104",
    job_title: "Solutions Architect",
    service_line: "Consulting",
    department: "Infrastructure Advisory",
    location: "Chicago, IL",
    posted_date: "2026-01-05",
    experience_required: "6-10 years",
    overall_score: 0.80,
    skill_match_score: 0.78,
    experience_score: 0.75,
    growth_potential_score: 0.68,
    matched_skills: ["AWS", "Client Management", "Python"],
    skill_gaps: ["Architecture Patterns", "Multi-Cloud", "Enterprise Design"],
    explanation: "Your AWS and client skills are valuable. Architecture expertise develops through experience and mentorship in this role.",
    salary_range: "$140k - $170k"
  },
  {
    id: "match-st-005",
    job_id: "job-105",
    job_title: "Data Engineering Manager",
    service_line: "Advisory",
    department: "Technology Consulting",
    location: "New York, NY",
    posted_date: "2026-01-03",
    experience_required: "7-12 years",
    overall_score: 0.77,
    skill_match_score: 0.73,
    experience_score: 0.82,
    growth_potential_score: 0.72,
    matched_skills: ["Python", "AWS", "Client Management"],
    skill_gaps: ["Team Leadership", "Project Management", "Data Architecture"],
    explanation: "Technical skills align well. Leadership and management skills develop through this role's responsibilities.",
    salary_range: "$150k - $180k"
  },
  {
    id: "match-st-006",
    job_id: "job-106",
    job_title: "Full Stack Developer - Data Products",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "Remote",
    posted_date: "2026-01-06",
    experience_required: "4-7 years",
    overall_score: 0.74,
    skill_match_score: 0.71,
    experience_score: 0.78,
    growth_potential_score: 0.73,
    matched_skills: ["Python", "Data Analysis"],
    skill_gaps: ["React", "JavaScript", "Frontend Development", "API Design"],
    explanation: "Your Python backend skills translate well. Frontend development is learnable and this role offers full-stack growth.",
    salary_range: "$110k - $140k"
  },
  {
    id: "match-st-007",
    job_id: "job-107",
    job_title: "Cloud Security Consultant",
    service_line: "Advisory",
    department: "Risk & Compliance",
    location: "Boston, MA",
    posted_date: "2026-01-07",
    experience_required: "5-9 years",
    overall_score: 0.76,
    skill_match_score: 0.72,
    experience_score: 0.79,
    growth_potential_score: 0.69,
    matched_skills: ["AWS", "Client Management"],
    skill_gaps: ["Security Frameworks", "Compliance", "IAM", "Security Best Practices"],
    explanation: "AWS knowledge is valuable. Security expertise develops through certifications and hands-on experience in this role.",
    salary_range: "$125k - $155k"
  },
  {
    id: "match-st-008",
    job_id: "job-108",
    job_title: "Business Intelligence Architect",
    service_line: "Consulting",
    department: "Analytics",
    location: "New York, NY",
    posted_date: "2026-01-04",
    experience_required: "6-10 years",
    overall_score: 0.79,
    skill_match_score: 0.76,
    experience_score: 0.81,
    growth_potential_score: 0.67,
    matched_skills: ["Data Analysis", "Client Management", "Python"],
    skill_gaps: ["BI Tools", "Data Warehousing", "ETL Architecture"],
    explanation: "Strong analytical foundation. BI architecture skills develop through project experience and tool training.",
    salary_range: "$135k - $165k"
  },
  {
    id: "match-st-009",
    job_id: "job-109",
    job_title: "Platform Engineer",
    service_line: "Advisory",
    department: "Technology Consulting",
    location: "Chicago, IL",
    posted_date: "2026-01-02",
    experience_required: "4-8 years",
    overall_score: 0.73,
    skill_match_score: 0.69,
    experience_score: 0.77,
    growth_potential_score: 0.74,
    matched_skills: ["AWS", "Python"],
    skill_gaps: ["Platform Design", "Microservices", "Container Orchestration"],
    explanation: "Cloud and Python skills provide foundation. Platform engineering concepts are learnable through mentorship.",
    salary_range: "$115k - $145k"
  },
  {
    id: "match-st-010",
    job_id: "job-110",
    job_title: "Data Science Manager",
    service_line: "Consulting",
    department: "Analytics",
    location: "San Francisco, CA",
    posted_date: "2026-01-08",
    experience_required: "7-12 years",
    overall_score: 0.81,
    skill_match_score: 0.77,
    experience_score: 0.84,
    growth_potential_score: 0.71,
    matched_skills: ["Data Analysis", "Python", "Client Management"],
    skill_gaps: ["ML Leadership", "Team Management", "Data Science Strategy"],
    explanation: "Strong analytical and client skills. Management and strategy expertise develops through leadership experience.",
    salary_range: "$155k - $190k"
  },
  {
    id: "match-st-011",
    job_id: "job-111",
    job_title: "Cloud Migration Specialist",
    service_line: "Advisory",
    department: "Infrastructure Advisory",
    location: "Remote",
    posted_date: "2026-01-05",
    experience_required: "5-9 years",
    overall_score: 0.78,
    skill_match_score: 0.74,
    experience_score: 0.80,
    growth_potential_score: 0.70,
    matched_skills: ["AWS", "Client Management", "Python"],
    skill_gaps: ["Migration Strategies", "Legacy Systems", "Change Management"],
    explanation: "AWS expertise is essential. Migration experience develops through project work and specialized training.",
    salary_range: "$130k - $160k"
  },
  {
    id: "match-st-012",
    job_id: "job-112",
    job_title: "Advanced Analytics Consultant",
    service_line: "Consulting",
    department: "Analytics",
    location: "New York, NY",
    posted_date: "2026-01-06",
    experience_required: "4-7 years",
    overall_score: 0.75,
    skill_match_score: 0.72,
    experience_score: 0.78,
    growth_potential_score: 0.72,
    matched_skills: ["Python", "Data Analysis", "Client Management"],
    skill_gaps: ["Advanced Statistics", "Predictive Modeling", "Experimental Design"],
    explanation: "Solid analytical foundation. Advanced techniques are learnable through coursework and project experience.",
    salary_range: "$120k - $150k"
  }
];

export const MOCK_MATCHES_EXPLORATORY: Match[] = [
  {
    id: "match-ex-001",
    job_id: "job-201",
    job_title: "Product Manager - Data Products",
    service_line: "Consulting",
    department: "Product Strategy",
    location: "San Francisco, CA",
    posted_date: "2026-01-01",
    experience_required: "5-10 years",
    overall_score: 0.65,
    skill_match_score: 0.60,
    experience_score: 0.70,
    growth_potential_score: 0.85,
    matched_skills: ["Data Analysis", "Client Management"],
    skill_gaps: ["Product Strategy", "Roadmapping", "Stakeholder Management", "Agile"],
    explanation: "This exploratory path combines your data expertise with product management. Your client management skills translate well, and you'd gain valuable strategic leadership experience.",
    salary_range: "$140k - $170k"
  },
  {
    id: "match-ex-002",
    job_id: "job-202",
    job_title: "Technical Sales Engineer",
    service_line: "Consulting",
    department: "Sales",
    location: "New York, NY",
    posted_date: "2026-01-03",
    experience_required: "3-7 years",
    overall_score: 0.62,
    skill_match_score: 0.58,
    experience_score: 0.66,
    growth_potential_score: 0.88,
    matched_skills: ["Client Management", "AWS", "Python"],
    skill_gaps: ["Sales Techniques", "Technical Demos", "Proposal Writing", "CRM"],
    explanation: "Your technical and client skills are valuable in sales engineering. This role offers high earning potential and business development experience.",
    salary_range: "$120k - $180k (commission)"
  },
  {
    id: "match-ex-003",
    job_id: "job-203",
    job_title: "Data Governance Lead",
    service_line: "Advisory",
    department: "Risk & Compliance",
    location: "Chicago, IL",
    posted_date: "2026-01-02",
    experience_required: "6-10 years",
    overall_score: 0.68,
    skill_match_score: 0.63,
    experience_score: 0.72,
    growth_potential_score: 0.82,
    matched_skills: ["Data Analysis", "Client Management"],
    skill_gaps: ["Data Governance", "Compliance", "Privacy Regulations", "Policy Development"],
    explanation: "Your data expertise provides foundation. Governance skills develop through specialized training and regulatory experience.",
    salary_range: "$135k - $165k"
  },
  {
    id: "match-ex-004",
    job_id: "job-204",
    job_title: "Innovation Consultant",
    service_line: "Consulting",
    department: "Innovation Lab",
    location: "Remote",
    posted_date: "2026-01-04",
    experience_required: "4-8 years",
    overall_score: 0.60,
    skill_match_score: 0.55,
    experience_score: 0.65,
    growth_potential_score: 0.90,
    matched_skills: ["Python", "Client Management"],
    skill_gaps: ["Design Thinking", "Innovation Frameworks", "Prototyping", "Emerging Tech"],
    explanation: "Technical and client skills are valuable. Innovation methodologies are learnable and this role offers exposure to cutting-edge work.",
    salary_range: "$125k - $155k"
  },
  {
    id: "match-ex-005",
    job_id: "job-205",
    job_title: "Change Management Consultant",
    service_line: "Advisory",
    department: "Organizational Transformation",
    location: "Boston, MA",
    posted_date: "2026-01-05",
    experience_required: "5-9 years",
    overall_score: 0.63,
    skill_match_score: 0.57,
    experience_score: 0.68,
    growth_potential_score: 0.87,
    matched_skills: ["Client Management", "Data Analysis"],
    skill_gaps: ["Change Management", "Organizational Psychology", "Training Design", "Stakeholder Engagement"],
    explanation: "Client management skills are essential. Change management expertise develops through certification and project experience.",
    salary_range: "$130k - $160k"
  },
  {
    id: "match-ex-006",
    job_id: "job-206",
    job_title: "AI Strategy Consultant",
    service_line: "Consulting",
    department: "Technology Consulting",
    location: "San Francisco, CA",
    posted_date: "2026-01-06",
    experience_required: "6-11 years",
    overall_score: 0.67,
    skill_match_score: 0.62,
    experience_score: 0.71,
    growth_potential_score: 0.83,
    matched_skills: ["Python", "Data Analysis", "Client Management"],
    skill_gaps: ["AI Strategy", "ML Business Applications", "Ethics", "AI Governance"],
    explanation: "Technical foundation is valuable. AI strategy skills develop through specialized training and strategic project work.",
    salary_range: "$145k - $175k"
  },
  {
    id: "match-ex-007",
    job_id: "job-207",
    job_title: "Digital Transformation Lead",
    service_line: "Advisory",
    department: "Digital Strategy",
    location: "New York, NY",
    posted_date: "2026-01-07",
    experience_required: "7-12 years",
    overall_score: 0.70,
    skill_match_score: 0.65,
    experience_score: 0.75,
    growth_potential_score: 0.80,
    matched_skills: ["Client Management", "AWS", "Data Analysis"],
    skill_gaps: ["Digital Strategy", "Transformation Frameworks", "Program Management", "Technology Roadmaps"],
    explanation: "Strong technical and client foundation. Digital transformation expertise develops through large-scale project leadership.",
    salary_range: "$150k - $185k"
  },
  {
    id: "match-ex-008",
    job_id: "job-208",
    job_title: "Research Scientist",
    service_line: "Advisory",
    department: "R&D",
    location: "Remote",
    posted_date: "2026-01-08",
    experience_required: "3-8 years",
    overall_score: 0.58,
    skill_match_score: 0.52,
    experience_score: 0.60,
    growth_potential_score: 0.92,
    matched_skills: ["Python", "Data Analysis"],
    skill_gaps: ["Research Methods", "Academic Writing", "Experimental Design", "Publication"],
    explanation: "Technical skills provide foundation. Research expertise develops through mentorship and academic collaboration.",
    salary_range: "$110k - $140k"
  },
  {
    id: "match-ex-009",
    job_id: "job-209",
    job_title: "Business Development Manager",
    service_line: "Consulting",
    department: "Business Development",
    location: "Chicago, IL",
    posted_date: "2026-01-04",
    experience_required: "5-10 years",
    overall_score: 0.64,
    skill_match_score: 0.59,
    experience_score: 0.69,
    growth_potential_score: 0.86,
    matched_skills: ["Client Management", "Data Analysis"],
    skill_gaps: ["Business Development", "Partnership Strategy", "Market Analysis", "Pitch Development"],
    explanation: "Client management skills are valuable. Business development expertise develops through sales training and market experience.",
    salary_range: "$135k - $170k (variable)"
  },
  {
    id: "match-ex-010",
    job_id: "job-210",
    job_title: "Sustainability Data Analyst",
    service_line: "Advisory",
    department: "ESG Consulting",
    location: "Boston, MA",
    posted_date: "2026-01-05",
    experience_required: "3-7 years",
    overall_score: 0.61,
    skill_match_score: 0.56,
    experience_score: 0.64,
    growth_potential_score: 0.89,
    matched_skills: ["Data Analysis", "Python"],
    skill_gaps: ["ESG Frameworks", "Sustainability Metrics", "Carbon Accounting", "Reporting Standards"],
    explanation: "Data analysis skills are essential. ESG expertise develops through specialized training and sustainability project work.",
    salary_range: "$105k - $135k"
  },
  {
    id: "match-ex-011",
    job_id: "job-211",
    job_title: "Technology Risk Consultant",
    service_line: "Advisory",
    department: "Risk & Compliance",
    location: "New York, NY",
    posted_date: "2026-01-06",
    experience_required: "4-8 years",
    overall_score: 0.66,
    skill_match_score: 0.61,
    experience_score: 0.70,
    growth_potential_score: 0.84,
    matched_skills: ["AWS", "Client Management", "Data Analysis"],
    skill_gaps: ["Risk Assessment", "Compliance Frameworks", "Audit", "Regulatory Requirements"],
    explanation: "Technical foundation is valuable. Risk and compliance expertise develops through certification and audit experience.",
    salary_range: "$125k - $155k"
  },
  {
    id: "match-ex-012",
    job_id: "job-212",
    job_title: "Learning & Development Specialist",
    service_line: "Consulting",
    department: "People & Culture",
    location: "Remote",
    posted_date: "2026-01-07",
    experience_required: "3-6 years",
    overall_score: 0.59,
    skill_match_score: 0.54,
    experience_score: 0.62,
    growth_potential_score: 0.91,
    matched_skills: ["Client Management", "Data Analysis"],
    skill_gaps: ["Instructional Design", "Adult Learning", "Training Delivery", "Curriculum Development"],
    explanation: "Client and analytical skills translate well. L&D expertise develops through education training and curriculum design experience.",
    salary_range: "$100k - $130k"
  }
];

export const MOCK_FILTER_OPTIONS = {
  departments: [
    "Technology Consulting",
    "Analytics",
    "Infrastructure Advisory",
    "Product Strategy",
    "Risk & Compliance",
    "Financial Reporting",
    "Innovation Lab",
    "Organizational Transformation",
    "Digital Strategy",
    "R&D",
    "Business Development",
    "ESG Consulting",
    "People & Culture",
    "Sales"
  ],
  locations: [
    "New York, NY",
    "Remote",
    "San Francisco, CA",
    "Chicago, IL",
    "Boston, MA"
  ],
  experience_levels: [
    "0-3 years",
    "3-5 years",
    "5-7 years",
    "7-10 years",
    "10+ years"
  ]
};
