"""
Pydantic schemas for deep job-candidate fit analysis.

These schemas define the response format for AI-powered deep analysis
using GPT-5.2 with reasoning capabilities.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


class ImportanceLevel(str, Enum):
    """How critical a skill is for success in the role."""
    CRITICAL = "critical"
    IMPORTANT = "important"
    NICE_TO_HAVE = "nice_to_have"


class GapSeverity(str, Enum):
    """Severity of a skill gap between candidate and role requirements."""
    NONE = "none"
    MINOR = "minor"
    MODERATE = "moderate"
    MAJOR = "major"


class SkillImpactAnalysis(BaseModel):
    """Detailed analysis of how a specific skill impacts the candidate-job fit."""

    skill_name: str = Field(
        ...,
        description="Name of the skill being analyzed"
    )
    importance_level: ImportanceLevel = Field(
        ...,
        description="How critical this skill is for the role"
    )
    why_it_matters: str = Field(
        ...,
        description="Explanation of why this skill is important for this specific role"
    )
    current_proficiency: Optional[str] = Field(
        default=None,
        description="Candidate's current proficiency level in this skill"
    )
    required_proficiency: str = Field(
        ...,
        description="Required proficiency level for the role"
    )
    gap_severity: GapSeverity = Field(
        ...,
        description="Severity of the gap between current and required proficiency"
    )
    learning_estimate: Optional[str] = Field(
        default=None,
        description="Estimated time to close the skill gap (e.g., '2-3 months')"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "skill_name": "Kubernetes",
                "importance_level": "critical",
                "why_it_matters": "The role involves managing containerized microservices at scale",
                "current_proficiency": "beginner",
                "required_proficiency": "advanced",
                "gap_severity": "moderate",
                "learning_estimate": "3-6 months with hands-on practice"
            }
        }


class ComplexAnalysis(BaseModel):
    """
    Comprehensive AI-generated analysis of candidate-job fit.

    Generated by GPT-5.2 with reasoning to provide deep insights
    about the match quality, growth opportunities, and success factors.
    """

    overall_fit_narrative: str = Field(
        ...,
        description="2-3 paragraph narrative analysis of the overall fit between candidate and role"
    )
    growth_opportunity: str = Field(
        ...,
        description="Analysis of career growth potential this role offers the candidate"
    )
    transition_reasoning: str = Field(
        ...,
        description="Explanation of why this transition makes sense (or doesn't) for the candidate's career"
    )
    matched_skill_impacts: List[SkillImpactAnalysis] = Field(
        ...,
        description="Detailed analysis of skills the candidate has that match the role"
    )
    gap_impacts: List[SkillImpactAnalysis] = Field(
        ...,
        description="Detailed analysis of skill gaps the candidate needs to address"
    )
    critical_success_factors: List[str] = Field(
        ...,
        max_length=5,
        description="Top 3-5 factors that will determine success in this role"
    )
    risk_factors: List[str] = Field(
        ...,
        max_length=5,
        description="Top 3-5 risks or concerns about this transition"
    )
    estimated_ramp_up: str = Field(
        ...,
        description="Estimated time for the candidate to become fully productive in the role"
    )
    comparable_roles: List[str] = Field(
        ...,
        description="Other roles that might be a good fit based on this analysis"
    )
    recommended_learning_path: List[str] = Field(
        ...,
        description="Recommended steps/resources for the candidate to prepare for this role"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "overall_fit_narrative": "Based on a comprehensive analysis of your background and this role's requirements, you represent a strong but stretch candidate for this Senior Cloud Architect position. Your extensive experience with AWS services and Python development provides a solid foundation, while your recent work on microservices architecture demonstrates relevant domain expertise.\n\nHowever, the role requires deeper expertise in Kubernetes orchestration and infrastructure-as-code practices that you're currently developing. This presents a meaningful growth opportunity rather than a blocker.\n\nYour track record of quickly learning new technologies and your demonstrated leadership in cross-functional teams positions you well for the collaborative aspects of this role.",
                "growth_opportunity": "This role offers significant career advancement by exposing you to enterprise-scale cloud architecture decisions. You'll gain hands-on experience with multi-region deployments and disaster recovery planning that will be invaluable for future principal engineer or architect roles.",
                "transition_reasoning": "This transition aligns with your stated goal of moving into infrastructure leadership. The 20% skill gap is manageable given your learning velocity, and the team's strong mentorship culture will support your development in areas like Terraform and advanced Kubernetes patterns.",
                "matched_skill_impacts": [],
                "gap_impacts": [],
                "critical_success_factors": [
                    "Rapidly developing Kubernetes proficiency to production level",
                    "Building relationships with the DevOps team for knowledge transfer",
                    "Leveraging existing AWS expertise to deliver quick wins",
                    "Proactively seeking feedback during the first 90 days"
                ],
                "risk_factors": [
                    "Steep learning curve on Terraform may slow initial contributions",
                    "Role requires on-call responsibilities you haven't experienced",
                    "Team expects autonomous decision-making from day one"
                ],
                "estimated_ramp_up": "4-6 months to full productivity, with meaningful contributions expected within the first month",
                "comparable_roles": [
                    "Cloud Infrastructure Engineer",
                    "Platform Engineer",
                    "DevOps Lead"
                ],
                "recommended_learning_path": [
                    "Complete CKA (Certified Kubernetes Administrator) certification",
                    "Build a personal project using Terraform to deploy a multi-service application",
                    "Study the team's existing infrastructure patterns in their documentation",
                    "Shadow on-call engineers for 2-3 rotations before taking shifts"
                ]
            }
        }
