"""
LLM Generator for SpringAIS Synthetic Data Generation

This module uses OpenAI models to generate realistic variation in employee data:
1. Metrics Generator (gpt-4o-mini): Generates specific metric values within ranges
2. Text Generator (gpt-4o): Generates feedback themes and notable achievements

Cost targets (per CONTEXT.md):
- Metrics: ~$0.04 total (900 employees × 50 tokens avg)
- Text: ~$1.89 total (900 employees × 150 tokens avg)

Usage:
    from llm_generator import LLMGenerator
    
    generator = LLMGenerator()
    
    # Generate metrics for a batch of employees
    metrics = generator.generate_metrics_batch(role_templates, count=100)
    
    # Generate text content
    feedback = generator.generate_feedback_themes("Manager", "Cloud & Infrastructure")
    achievement = generator.generate_notable_achievement("Manager", ["AWS", "Strategy"])
"""

import os
import json
import time
import random
import logging
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from functools import lru_cache
from datetime import datetime

# OpenAI import with fallback
try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False

from role_templates import RoleTemplate, PerformanceRanges

logger = logging.getLogger(__name__)


@dataclass
class TokenUsage:
    """Tracks token usage and estimated costs."""
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    
    # Pricing per 1M tokens (as of 2024, update as needed)
    # gpt-4o-mini: $0.15 input, $0.60 output per 1M
    # gpt-4o: $2.50 input, $10.00 output per 1M
    PRICING = {
        "gpt-4o-mini": {"input": 0.15, "output": 0.60},
        "gpt-4o": {"input": 2.50, "output": 10.00},
    }
    
    def add(self, prompt: int, completion: int):
        self.prompt_tokens += prompt
        self.completion_tokens += completion
        self.total_tokens += prompt + completion
    
    def estimate_cost(self, model: str) -> float:
        """Estimate cost in USD based on model pricing."""
        if model not in self.PRICING:
            return 0.0
        pricing = self.PRICING[model]
        input_cost = (self.prompt_tokens / 1_000_000) * pricing["input"]
        output_cost = (self.completion_tokens / 1_000_000) * pricing["output"]
        return input_cost + output_cost


@dataclass
class GeneratedMetrics:
    """Performance metrics generated by LLM with realistic variation."""
    utilization: int  # %
    billing_rate: int  # $/hr
    realization: int  # %
    quality_score: float  # 1-5 scale
    training_hours: int  # per year
    client_feedback: float  # 1-5 scale
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "utilization": self.utilization,
            "billing_rate": self.billing_rate,
            "realization": self.realization,
            "quality_score": round(self.quality_score, 2),
            "training_hours": self.training_hours,
            "client_feedback": round(self.client_feedback, 2),
        }


@dataclass
class GeneratedText:
    """Text content generated by LLM for employee profiles."""
    feedback_themes: List[str]  # 3-5 phrases
    notable_achievement: str  # 1 sentence
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "feedback_themes": self.feedback_themes,
            "notable_achievement": self.notable_achievement,
        }


class LLMGenerator:
    """
    Generator for synthetic employee data using OpenAI models.
    
    Uses two models:
    - gpt-4o-mini: Cheap, fast metric generation
    - gpt-4o: Higher quality text generation
    """
    
    # Model configuration
    METRICS_MODEL = "gpt-4o-mini"
    TEXT_MODEL = "gpt-4o"
    
    # Batch sizes for API efficiency
    METRICS_BATCH_SIZE = 100  # Generate 100 employees per API call
    TEXT_BATCH_SIZE = 20  # Generate 20 employees per API call
    
    # Retry configuration
    MAX_RETRIES = 3
    RETRY_DELAY = 2.0  # seconds
    
    def __init__(
        self,
        api_key: Optional[str] = None,
        use_mock: bool = False,
    ):
        """
        Initialize LLM Generator.
        
        Args:
            api_key: OpenAI API key (defaults to OPENAI_API_KEY env var)
            use_mock: If True, generate mock data without API calls (for testing)
        """
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.use_mock = use_mock
        
        # Token tracking
        self.metrics_usage = TokenUsage()
        self.text_usage = TokenUsage()
        
        # Cache for similar roles (reduces API calls)
        self._feedback_cache: Dict[str, List[str]] = {}
        self._achievement_cache: Dict[str, List[str]] = {}
        
        # Initialize OpenAI client
        self.client = None
        if OPENAI_AVAILABLE and self.api_key and not use_mock:
            self.client = OpenAI(api_key=self.api_key)
        elif not use_mock and not self.api_key:
            logger.warning(
                "No OPENAI_API_KEY found. Using mock mode. "
                "Set OPENAI_API_KEY environment variable for real generation."
            )
            self.use_mock = True
    
    def _call_api_with_retry(
        self,
        model: str,
        messages: List[Dict[str, str]],
        temperature: float = 0.7,
        max_tokens: int = 1000,
    ) -> Tuple[Optional[str], int, int]:
        """
        Call OpenAI API with retry logic.
        
        Returns:
            Tuple of (response_text, prompt_tokens, completion_tokens)
        """
        if self.use_mock or not self.client:
            return None, 0, 0
        
        for attempt in range(self.MAX_RETRIES):
            try:
                response = self.client.chat.completions.create(
                    model=model,
                    messages=messages,
                    temperature=temperature,
                    max_tokens=max_tokens,
                )
                
                content = response.choices[0].message.content
                usage = response.usage
                
                return content, usage.prompt_tokens, usage.completion_tokens
                
            except Exception as e:
                logger.warning(f"API call failed (attempt {attempt + 1}/{self.MAX_RETRIES}): {e}")
                if attempt < self.MAX_RETRIES - 1:
                    time.sleep(self.RETRY_DELAY * (attempt + 1))
                else:
                    logger.error(f"All {self.MAX_RETRIES} API attempts failed")
                    raise
        
        return None, 0, 0
    
    # =========================================================================
    # TASK 3: METRICS GENERATION (gpt-4o-mini)
    # =========================================================================
    
    def _generate_mock_metrics(self, ranges: PerformanceRanges) -> GeneratedMetrics:
        """Generate mock metrics using random values within ranges (for testing)."""
        return GeneratedMetrics(
            utilization=random.randint(ranges.utilization[0], ranges.utilization[1]),
            billing_rate=random.randint(ranges.billing_rate[0], ranges.billing_rate[1]),
            realization=random.randint(ranges.realization[0], ranges.realization[1]),
            quality_score=round(random.uniform(ranges.quality_score[0], ranges.quality_score[1]), 2),
            training_hours=random.randint(ranges.training_hours[0], ranges.training_hours[1]),
            client_feedback=round(random.uniform(ranges.client_feedback[0], ranges.client_feedback[1]), 2),
        )
    
    def generate_metrics(self, template: RoleTemplate) -> GeneratedMetrics:
        """
        Generate performance metrics for a single employee.
        
        Uses gpt-4o-mini for cheap variation or mock mode for testing.
        """
        if self.use_mock:
            return self._generate_mock_metrics(template.performance_ranges)
        
        ranges = template.performance_ranges
        
        prompt = f"""Generate realistic performance metrics for an EY {template.service_line} {template.role_name}.

Constraints (MUST be within these exact ranges):
- utilization: {ranges.utilization[0]}-{ranges.utilization[1]}%
- billing_rate: ${ranges.billing_rate[0]}-${ranges.billing_rate[1]}/hr
- realization: {ranges.realization[0]}-{ranges.realization[1]}%
- quality_score: {ranges.quality_score[0]}-{ranges.quality_score[1]} (out of 5)
- training_hours: {ranges.training_hours[0]}-{ranges.training_hours[1]} per year
- client_feedback: {ranges.client_feedback[0]}-{ranges.client_feedback[1]} (out of 5)

Return ONLY a JSON object with these 6 numeric fields, nothing else:
{{"utilization": X, "billing_rate": X, "realization": X, "quality_score": X.X, "training_hours": X, "client_feedback": X.X}}"""

        response, prompt_tokens, completion_tokens = self._call_api_with_retry(
            model=self.METRICS_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.8,
            max_tokens=100,
        )
        
        self.metrics_usage.add(prompt_tokens, completion_tokens)
        
        if response:
            try:
                # Parse JSON response
                data = json.loads(response.strip())
                return GeneratedMetrics(
                    utilization=self._clamp_int(data.get("utilization", 75), ranges.utilization),
                    billing_rate=self._clamp_int(data.get("billing_rate", 150), ranges.billing_rate),
                    realization=self._clamp_int(data.get("realization", 90), ranges.realization),
                    quality_score=self._clamp_float(data.get("quality_score", 4.0), ranges.quality_score),
                    training_hours=self._clamp_int(data.get("training_hours", 40), ranges.training_hours),
                    client_feedback=self._clamp_float(data.get("client_feedback", 4.2), ranges.client_feedback),
                )
            except (json.JSONDecodeError, KeyError) as e:
                logger.warning(f"Failed to parse metrics response: {e}. Using mock.")
        
        return self._generate_mock_metrics(ranges)
    
    def generate_metrics_batch(
        self,
        templates: List[Tuple[RoleTemplate, int]],  # List of (template, count) tuples
    ) -> List[GeneratedMetrics]:
        """
        Generate metrics for a batch of employees efficiently.
        
        Batches API calls for cost efficiency (~100 employees per call).
        
        Args:
            templates: List of (RoleTemplate, count) tuples
            
        Returns:
            List of GeneratedMetrics for all employees
        """
        all_metrics = []
        
        # Flatten into individual employee requests
        employee_requests = []
        for template, count in templates:
            for _ in range(count):
                employee_requests.append(template)
        
        # Process in batches
        for i in range(0, len(employee_requests), self.METRICS_BATCH_SIZE):
            batch = employee_requests[i:i + self.METRICS_BATCH_SIZE]
            batch_metrics = self._generate_metrics_batch_internal(batch)
            all_metrics.extend(batch_metrics)
            
            # Log progress
            logger.info(f"Generated metrics for {len(all_metrics)}/{len(employee_requests)} employees")
        
        return all_metrics
    
    def _generate_metrics_batch_internal(
        self,
        templates: List[RoleTemplate],
    ) -> List[GeneratedMetrics]:
        """Generate metrics for a batch via single API call."""
        if self.use_mock:
            return [self._generate_mock_metrics(t.performance_ranges) for t in templates]
        
        # Build batch prompt
        batch_specs = []
        for idx, template in enumerate(templates):
            ranges = template.performance_ranges
            batch_specs.append(
                f'{idx}: {template.service_line} {template.role_name} - '
                f'util:{ranges.utilization[0]}-{ranges.utilization[1]}, '
                f'bill:${ranges.billing_rate[0]}-{ranges.billing_rate[1]}, '
                f'real:{ranges.realization[0]}-{ranges.realization[1]}, '
                f'qual:{ranges.quality_score[0]}-{ranges.quality_score[1]}, '
                f'train:{ranges.training_hours[0]}-{ranges.training_hours[1]}, '
                f'fb:{ranges.client_feedback[0]}-{ranges.client_feedback[1]}'
            )
        
        prompt = f"""Generate realistic performance metrics for {len(templates)} employees.
Each employee has different ranges. Generate varied but realistic values within each range.

Employees and their ranges:
{chr(10).join(batch_specs)}

Return a JSON array with {len(templates)} objects, each with: utilization, billing_rate, realization, quality_score, training_hours, client_feedback.
Example format: [{{"utilization":82,"billing_rate":165,"realization":91,"quality_score":4.1,"training_hours":42,"client_feedback":4.3}}, ...]"""

        response, prompt_tokens, completion_tokens = self._call_api_with_retry(
            model=self.METRICS_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9,
            max_tokens=len(templates) * 80,  # ~80 tokens per employee
        )
        
        self.metrics_usage.add(prompt_tokens, completion_tokens)
        
        if response:
            try:
                # Parse JSON array response
                data = json.loads(response.strip())
                if isinstance(data, list) and len(data) >= len(templates):
                    results = []
                    for idx, template in enumerate(templates):
                        ranges = template.performance_ranges
                        item = data[idx]
                        results.append(GeneratedMetrics(
                            utilization=self._clamp_int(item.get("utilization", 75), ranges.utilization),
                            billing_rate=self._clamp_int(item.get("billing_rate", 150), ranges.billing_rate),
                            realization=self._clamp_int(item.get("realization", 90), ranges.realization),
                            quality_score=self._clamp_float(item.get("quality_score", 4.0), ranges.quality_score),
                            training_hours=self._clamp_int(item.get("training_hours", 40), ranges.training_hours),
                            client_feedback=self._clamp_float(item.get("client_feedback", 4.2), ranges.client_feedback),
                        ))
                    return results
            except (json.JSONDecodeError, KeyError, IndexError) as e:
                logger.warning(f"Failed to parse batch metrics: {e}. Using mock for batch.")
        
        # Fallback to mock
        return [self._generate_mock_metrics(t.performance_ranges) for t in templates]
    
    # =========================================================================
    # TASK 4: TEXT GENERATION (gpt-4o)
    # =========================================================================
    
    def _generate_mock_feedback_themes(self, role: str, focus_area: str, service_line: str = None) -> List[str]:
        """Generate mock feedback themes for testing with high variety."""
        # Expanded theme pools for variety (50+ unique per service line)
        base_themes = {
            "Assurance": [
                "meticulous attention to detail", "strong technical knowledge", "reliable and thorough",
                "excellent documentation skills", "proactive risk identification", "clear communication with clients",
                "collaborative team player", "strong work ethic", "exceptional audit methodology",
                "deep GAAP expertise", "outstanding analytical rigor", "effective time management",
                "builds trust with clients", "mentors junior staff effectively", "anticipates audit risks",
                "strong SOX compliance knowledge", "maintains composure under pressure", "delivers high-quality workpapers",
                "excellent stakeholder communication", "demonstrates professional skepticism", "consistent quality reviewer",
                "adept at complex technical issues", "effective at managing deadlines", "strong internal controls expertise",
                "exceeds client expectations", "highly organized approach", "demonstrates integrity consistently",
                "excellent problem identification", "strong financial reporting knowledge", "valued team contributor",
                "adapts quickly to new standards", "thorough testing procedures", "builds lasting client relationships",
            ],
            "Tax": [
                "deep tax code expertise", "thorough research skills", "client-focused approach",
                "stays current on regulations", "creative problem solver", "reliable and responsive",
                "excellent technical writing", "strong analytical abilities", "exceptional tax planning skills",
                "navigates complex tax issues", "proactive compliance approach", "builds client confidence",
                "strong IRS representation skills", "effective multistate tax knowledge", "trusted tax advisor",
                "excellent at tax controversy", "innovative structuring ideas", "strong transfer pricing expertise",
                "keeps clients well-informed", "anticipates regulatory changes", "detailed tax provision work",
                "strong M&A tax experience", "effective at credits and incentives", "builds strong team rapport",
                "exceptional research abilities", "communicates complex issues clearly", "strong international tax knowledge",
                "reliable tax compliance delivery", "creative yet compliant solutions", "valued for technical depth",
                "consistent high-quality work", "strong ethics and integrity", "effective time management",
            ],
            "Consulting": [
                "strategic thinker", "excellent presentation skills", "drives results effectively",
                "builds strong client relationships", "adaptable to change", "collaborative leadership",
                "innovative problem solver", "strong project management", "exceptional stakeholder management",
                "delivers complex transformations", "builds high-performing teams", "thought leader in specialty",
                "navigates ambiguity well", "drives sustainable change", "outstanding executive presence",
                "effective change management", "strong business development", "mentors emerging talent",
                "balances multiple priorities", "client-centric approach", "delivers on commitments",
                "excellent workshop facilitation", "translates strategy to action", "builds lasting partnerships",
                "strong data-driven insights", "effective at rapid prototyping", "outstanding technical depth",
                "creates innovative solutions", "manages risk effectively", "strong vendor management",
                "exceptional communication skills", "delivers measurable outcomes", "trusted advisor to clients",
            ],
        }
        
        # Determine service line from focus_area if not provided
        if not service_line:
            service_line = "Consulting" if any(x in focus_area for x in ["Cloud", "Data", "Cyber", "AI", "Strategy", "Operations"]) else (
                "Assurance" if any(x in focus_area for x in ["Audit", "Financial", "Risk", "SEC"]) else "Tax"
        )
        
        themes = base_themes.get(service_line, base_themes["Consulting"])
        # Random sample 3-5 themes for variety
        return random.sample(themes, min(random.randint(3, 5), len(themes)))
    
    def _generate_mock_achievement(self, role: str, skills: List[str], service_line: str = "Consulting", level: int = 3) -> str:
        """Generate mock notable achievement for testing with high variety."""
        skill = skills[0] if skills else "key initiative"
        
        # Level-appropriate achievements (entry=1-3, mid=4-6, senior=7-9)
        entry_achievements = [
            f"Received outstanding feedback from client engagement team for {skill} deliverables",
            f"Completed professional certification in {skill} ahead of schedule",
            f"Recognized by manager for exceptional work quality on first major engagement",
            f"Contributed key analysis that identified $500K in client cost savings",
            f"Selected for accelerated development program based on first-year performance",
            f"Received highest peer feedback scores among new hires in service line",
            f"Successfully completed complex testing procedures with zero rework required",
            f"Praised by partner for proactive communication and attention to detail",
            f"Developed reusable template that improved team efficiency by 15%",
            f"Received client commendation letter for professional conduct and responsiveness",
        ]
        
        mid_achievements = [
            f"Led successful implementation of {skill} for Fortune 500 client with zero defects",
            f"Developed innovative approach that reduced project timeline by 25%",
            f"Mentored 5 junior team members, 3 promoted within 18 months",
            f"Won internal excellence award for outstanding client feedback scores",
            f"Pioneered new methodology in {skill} now adopted across the practice",
            f"Successfully delivered complex engagement under aggressive timeline and budget",
            f"Identified and resolved critical risk that saved client $1.2M in potential issues",
            f"Built reusable framework for {skill} that became practice standard",
            f"Received perfect client satisfaction scores across all engagements this year",
            f"Led cross-functional team to deliver award-winning client solution",
            f"Authored thought leadership piece on {skill} published in industry journal",
            f"Spearheaded process improvement initiative that increased team utilization by 8%",
        ]
        
        senior_achievements = [
            f"Secured $2M in additional project revenue through strategic relationship building",
            f"Recognized for exceptional client delivery and promoted ahead of standard cycle",
            f"Led firm-wide initiative in {skill} that generated $5M in new business",
            f"Developed strategic partnership with key industry player worth $3M annually",
            f"Served as executive sponsor for firm's largest client transformation program",
            f"Built and led high-performing team that achieved 95%+ client satisfaction",
            f"Authored firm's definitive guidance on {skill} best practices",
            f"Led successful proposal that won $8M multi-year engagement",
            f"Recognized as firm subject matter expert and speaks at industry conferences",
            f"Achieved highest revenue generation in practice area for consecutive years",
            f"Led acquisition integration that retained 100% of key client relationships",
            f"Developed innovative service offering that created new revenue stream of $4M",
        ]
        
        # Select based on level
        if level <= 3:
            achievements = entry_achievements
        elif level <= 6:
            achievements = mid_achievements
        else:
            achievements = senior_achievements
        
        return random.choice(achievements)
    
    @lru_cache(maxsize=100)
    def _get_cached_feedback_themes(self, cache_key: str) -> Optional[List[str]]:
        """Check cache for similar role feedback themes."""
        return self._feedback_cache.get(cache_key)
    
    def generate_feedback_themes(
        self,
        role: str,
        focus_area: str,
        service_line: str = "Consulting",
        level: int = 3,
    ) -> List[str]:
        """
        Generate 3-5 realistic feedback themes for an employee.
        
        Uses caching for similar roles to reduce API calls.
        
        Args:
            role: Employee's role (e.g., "Manager")
            focus_area: Area of specialization (e.g., "Cloud & Infrastructure")
            service_line: Service line ("Assurance", "Tax", "Consulting")
            level: Role level (1-9)
            
        Returns:
            List of 3-5 feedback theme phrases
        """
        if self.use_mock:
            return self._generate_mock_feedback_themes(role, focus_area, service_line)
        
        # Check cache
        cache_key = f"{service_line}:{role}:{focus_area}"
        if cache_key in self._feedback_cache:
            # Return cached with slight variation
            cached = self._feedback_cache[cache_key]
            return random.sample(cached, min(random.randint(3, 5), len(cached)))
        
        prompt = f"""Generate 8 realistic performance feedback themes for an EY {service_line} {role} 
specializing in {focus_area}.

These should be short phrases (2-5 words) that would appear in peer/manager feedback.
Mix of technical competencies and soft skills appropriate for level {level} (1=entry, 9=partner).

Examples: "strong analytical skills", "drives results effectively", "excellent client rapport"

Return ONLY a JSON array of 8 strings:
["theme1", "theme2", "theme3", "theme4", "theme5", "theme6", "theme7", "theme8"]"""

        response, prompt_tokens, completion_tokens = self._call_api_with_retry(
            model=self.TEXT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9,
            max_tokens=200,
        )
        
        self.text_usage.add(prompt_tokens, completion_tokens)
        
        if response:
            try:
                themes = json.loads(response.strip())
                if isinstance(themes, list) and len(themes) >= 3:
                    # Cache for reuse
                    self._feedback_cache[cache_key] = themes
                    return random.sample(themes, min(random.randint(3, 5), len(themes)))
            except json.JSONDecodeError as e:
                logger.warning(f"Failed to parse feedback themes: {e}")
        
        return self._generate_mock_feedback_themes(role, focus_area, service_line)
    
    def generate_notable_achievement(
        self,
        role: str,
        skills: List[str],
        service_line: str = "Consulting",
        focus_area: str = "Strategy",
        level: int = 3,
    ) -> str:
        """
        Generate a notable achievement statement for an employee.
        
        Args:
            role: Employee's role
            skills: List of employee's key skills
            service_line: Service line
            focus_area: Area of specialization
            level: Role level
            
        Returns:
            Single sentence describing a notable achievement
        """
        if self.use_mock:
            return self._generate_mock_achievement(role, skills, service_line, level)
        
        # Check cache for similar role
        cache_key = f"{service_line}:{role}:{focus_area}"
        if cache_key in self._achievement_cache and random.random() < 0.3:
            # 30% chance to reuse with variation
            achievements = self._achievement_cache[cache_key]
            return random.choice(achievements)
        
        skills_str = ", ".join(skills[:5]) if skills else "general business"
        
        prompt = f"""Generate a single notable achievement sentence for an EY {service_line} {role}.

Context:
- Specialization: {focus_area}
- Key skills: {skills_str}
- Level: {level}/9 (1=entry, 9=partner)

The achievement should be:
- Specific and measurable where possible
- Appropriate for their level (entry=learning achievements, senior=leadership/revenue)
- 1 sentence, 15-25 words
- Professional tone

Return ONLY the achievement sentence, no quotes or explanation."""

        response, prompt_tokens, completion_tokens = self._call_api_with_retry(
            model=self.TEXT_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.95,
            max_tokens=60,
        )
        
        self.text_usage.add(prompt_tokens, completion_tokens)
        
        if response:
            achievement = response.strip().strip('"')
            # Cache for potential reuse
            if cache_key not in self._achievement_cache:
                self._achievement_cache[cache_key] = []
            self._achievement_cache[cache_key].append(achievement)
            if len(self._achievement_cache[cache_key]) > 10:
                self._achievement_cache[cache_key] = self._achievement_cache[cache_key][-10:]
            return achievement
        
        return self._generate_mock_achievement(role, skills, service_line, level)
    
    def generate_text_batch(
        self,
        employees: List[Dict[str, Any]],
    ) -> List[GeneratedText]:
        """
        Generate text content (feedback + achievements) for a batch of employees.
        
        Args:
            employees: List of dicts with role, skills, service_line, focus_area, level
            
        Returns:
            List of GeneratedText objects
        """
        results = []
        
        for i in range(0, len(employees), self.TEXT_BATCH_SIZE):
            batch = employees[i:i + self.TEXT_BATCH_SIZE]
            
            for emp in batch:
                feedback = self.generate_feedback_themes(
                    role=emp.get("role", "Consultant"),
                    focus_area=emp.get("focus_area", "Strategy"),
                    service_line=emp.get("service_line", "Consulting"),
                    level=emp.get("level", 3),
                )
                achievement = self.generate_notable_achievement(
                    role=emp.get("role", "Consultant"),
                    skills=emp.get("skills", []),
                    service_line=emp.get("service_line", "Consulting"),
                    focus_area=emp.get("focus_area", "Strategy"),
                    level=emp.get("level", 3),
                )
                results.append(GeneratedText(
                    feedback_themes=feedback,
                    notable_achievement=achievement,
                ))
            
            logger.info(f"Generated text for {len(results)}/{len(employees)} employees")
        
        return results
    
    # =========================================================================
    # UTILITY METHODS
    # =========================================================================
    
    @staticmethod
    def _clamp_int(value: Any, bounds: Tuple[int, int]) -> int:
        """Clamp a value to integer bounds."""
        try:
            v = int(value)
            return max(bounds[0], min(bounds[1], v))
        except (ValueError, TypeError):
            return (bounds[0] + bounds[1]) // 2
    
    @staticmethod
    def _clamp_float(value: Any, bounds: Tuple[float, float]) -> float:
        """Clamp a value to float bounds."""
        try:
            v = float(value)
            return max(bounds[0], min(bounds[1], v))
        except (ValueError, TypeError):
            return (bounds[0] + bounds[1]) / 2
    
    def get_cost_summary(self) -> Dict[str, Any]:
        """Get summary of token usage and estimated costs."""
        metrics_cost = self.metrics_usage.estimate_cost(self.METRICS_MODEL)
        text_cost = self.text_usage.estimate_cost(self.TEXT_MODEL)
        
        return {
            "metrics": {
                "model": self.METRICS_MODEL,
                "prompt_tokens": self.metrics_usage.prompt_tokens,
                "completion_tokens": self.metrics_usage.completion_tokens,
                "total_tokens": self.metrics_usage.total_tokens,
                "estimated_cost_usd": round(metrics_cost, 4),
            },
            "text": {
                "model": self.TEXT_MODEL,
                "prompt_tokens": self.text_usage.prompt_tokens,
                "completion_tokens": self.text_usage.completion_tokens,
                "total_tokens": self.text_usage.total_tokens,
                "estimated_cost_usd": round(text_cost, 4),
            },
            "total_estimated_cost_usd": round(metrics_cost + text_cost, 4),
            "cache_stats": {
                "feedback_cache_entries": len(self._feedback_cache),
                "achievement_cache_entries": len(self._achievement_cache),
            },
        }
    
    def print_cost_summary(self):
        """Print a formatted cost summary."""
        summary = self.get_cost_summary()
        
        print("\n" + "=" * 60)
        print("LLM GENERATION COST SUMMARY")
        print("=" * 60)
        
        print(f"\n📊 Metrics Generation ({summary['metrics']['model']})")
        print(f"   Prompt tokens:     {summary['metrics']['prompt_tokens']:,}")
        print(f"   Completion tokens: {summary['metrics']['completion_tokens']:,}")
        print(f"   Estimated cost:    ${summary['metrics']['estimated_cost_usd']:.4f}")
        
        print(f"\n📝 Text Generation ({summary['text']['model']})")
        print(f"   Prompt tokens:     {summary['text']['prompt_tokens']:,}")
        print(f"   Completion tokens: {summary['text']['completion_tokens']:,}")
        print(f"   Estimated cost:    ${summary['text']['estimated_cost_usd']:.4f}")
        
        print(f"\n💰 TOTAL ESTIMATED COST: ${summary['total_estimated_cost_usd']:.4f}")
        
        print(f"\n📦 Cache Stats")
        print(f"   Feedback themes cached:  {summary['cache_stats']['feedback_cache_entries']} role combinations")
        print(f"   Achievements cached:     {summary['cache_stats']['achievement_cache_entries']} role combinations")
        
        print("=" * 60)


def test_generator():
    """Test the LLM generator with sample data."""
    from role_templates import get_role_template, get_all_roles
    
    print("\n" + "=" * 60)
    print("TESTING LLM GENERATOR")
    print("=" * 60)
    
    # Test in mock mode first
    print("\n1. Testing MOCK mode (no API calls)...")
    mock_gen = LLMGenerator(use_mock=True)
    
    # Get a sample template
    template = get_role_template("Consulting", "Manager")
    
    # Test single metric generation
    print("\n   Single metric generation:")
    metrics = mock_gen.generate_metrics(template)
    print(f"   {metrics.to_dict()}")
    
    # Test feedback themes
    print("\n   Feedback themes:")
    themes = mock_gen.generate_feedback_themes("Manager", "Cloud & Infrastructure", "Consulting", 6)
    print(f"   {themes}")
    
    # Test notable achievement
    print("\n   Notable achievement:")
    achievement = mock_gen.generate_notable_achievement(
        "Manager", 
        ["AWS", "Strategy", "Client Management"],
        "Consulting",
        "Cloud & Infrastructure",
        6
    )
    print(f"   {achievement}")
    
    # Test batch metrics (10 employees)
    print("\n   Batch metric generation (10 employees):")
    batch_templates = [
        (get_role_template("Assurance", "Senior"), 3),
        (get_role_template("Tax", "Manager"), 3),
        (get_role_template("Consulting", "Consultant"), 4),
    ]
    batch_metrics = mock_gen.generate_metrics_batch(batch_templates)
    print(f"   Generated {len(batch_metrics)} metric sets")
    print(f"   Sample: {batch_metrics[0].to_dict()}")
    
    mock_gen.print_cost_summary()
    
    # Test with real API if key is available
    print("\n\n2. Testing LIVE mode (with API)...")
    live_gen = LLMGenerator(use_mock=False)
    
    if live_gen.use_mock:
        print("   ⚠️  No API key found, skipping live tests")
        print("   Set OPENAI_API_KEY environment variable to test live generation")
    else:
        print("   API key found, running live tests...")
        
        # Test single metric
        print("\n   Live metric generation:")
        metrics = live_gen.generate_metrics(template)
        print(f"   {metrics.to_dict()}")
        
        # Test feedback themes
        print("\n   Live feedback themes:")
        themes = live_gen.generate_feedback_themes("Manager", "Cloud & Infrastructure", "Consulting", 6)
        print(f"   {themes}")
        
        # Test achievement
        print("\n   Live notable achievement:")
        achievement = live_gen.generate_notable_achievement(
            "Manager",
            ["AWS", "Strategy", "Client Management"],
            "Consulting",
            "Cloud & Infrastructure",
            6
        )
        print(f"   {achievement}")
        
        live_gen.print_cost_summary()
    
    print("\n✅ All tests completed!")
    return True


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    test_generator()

